# Generated by Django 5.1.6 on 2025-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='username',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
